---
rep_user: replicauser
rep_pswd: replicauser

pg_cron_prefix: /opt/cronjobs/postgres
pg_cron_bins: "{{pg_cron_prefix}}/bin"
pg_cron_confs: "{{pg_cron_prefix}}/etc"
pg_cron_dump_script_name: pg-slave-dump.sh
pg_cron_dump_script: "{{pg_cron_bins}}/{{pg_cron_dump_script_name}}"
pg_cron_logrotate_script_name: logrotate_user_wrapper.sh
pg_cron_logrotate_script: "{{pg_cron_bins}}/{{pg_cron_logrotate_script_name}}"
pg_cron_logrotate_conf_name: pg_dump_logrotate.conf
pg_cron_logrotate_conf: "{{pg_cron_confs}}/{{pg_cron_logrotate_conf_name}}"
pg_dump_dirs:
  - { dir: /opt/cronjobs, mode: 775, owner: root, group: root }
  - { dir: "{{pg_cron_prefix}}", mode: 755, owner: postgres, group: postgres }
  - { dir: "{{pg_cron_bins}}", mode: 755, owner: postgres, group: postgres }
  - { dir: "{{pg_cron_confs}}", mode: 755, owner: postgres, group: postgres }
  - { dir: /var/backups, mode: 755, owner: root, group: root }
  - { dir: /var/backups/postgres, mode: 770, owner: root, group: postgres }
pg_dumps_scripts:
  - { name: "{{pg_cron_dump_script_name}}", srcd: cron, destd: "{{pg_cron_bins}}", mode: 755, owner: postgres, group: postgres }
  - { name: job_logger.source.sh, srcd: cron, destd: "{{pg_cron_bins}}", mode: 644, owner: postgres, group: postgres }
  - { name: "{{pg_cron_logrotate_script_name}}", srcd: cron/logrotate, destd: "{{pg_cron_bins}}", mode: 755, owner: postgres, group: postgres }
  - { name: "{{pg_cron_logrotate_conf_name}}", srcd: cron/logrotate, destd: "{{pg_cron_confs}}", mode: 644, owner: postgres, group: postgres }
...
